CHANGELOG.md, nextjs/package.json, nextjs/src/app/[locale]/page.tsx, nextjs/src/app/homepage.tsx, nextjs/src/app/page.tsx, nextjs/src/lib/constants.ts, nextjs/src/lib/strapi.ts, strapi/package.json
Update content in fronten when new verison was published through strapi
=> Staging fixes

strapi/.env.example, strapi/config/middlewares.ts, strapi/config/plugins.ts, strapi/package-lock.json, strapi/package.json
Enable media upload by DigitalOcean spaces
=> feat (strapi): do spaces for file upload

nextjs/src/app/[locale]/theme/page.tsx, nextjs/src/components/cards/card-image.tsx, nextjs/src/components/sections/section-card-wide.tsx
=> feat: Add color option to CardImage, SectionCardWide components

nextjs/src/app/[locale]/theme/page.tsx, nextjs/src/app/[locale]/theme/texts.ts, nextjs/src/components/sections/section-quote.tsx, nextjs/tailwind.config.ts
=> feat: Create responsive SectionQuote

CHANGELOG.md, nextjs/package-lock.json, nextjs/package.json, nextjs/src/app/[locale]/theme/page.tsx, nextjs/src/app/[locale]/theme/texts.ts, nextjs/src/app/text.css, nextjs/src/components/button.tsx, nextjs/src/components/sections/section-calendly.tsx, nextjs/src/components/sections/section-group.css, nextjs/src/components/sections/section-group.tsx, nextjs/src/components/sections/section-whitepaper.tsx, nextjs/src/components/title.tsx, strapi/package-lock.json, strapi/package.json
- feat: calendly section (#39)
- feat: two column markdown (#38)
- feat: white paper download (#37)
=> Release 0.7.0

CHANGELOG.md, nextjs/package-lock.json, nextjs/package.json, nextjs/src/components/form/messages.ts, nextjs/src/components/form/standard-form.tsx, strapi/package-lock.json, strapi/package.json
- fix: hotfix theme preview page
=> Release 0.7.1

.vscode/settings.json, nextjs/.prettierrc, nextjs/next.config.mjs, nextjs/src/app/[locale]/theme/page.tsx, nextjs/src/app/[locale]/theme/texts.ts, nextjs/src/app/text.css, nextjs/src/components/cards/card-colored.tsx, nextjs/src/components/cards/card-message.tsx
=> Card with Message Icon as Header

.github/workflows/ci.yml, .vscode/settings.json, CHANGELOG.md, nextjs/.prettierrc, nextjs/next.config.mjs, nextjs/package-lock.json, nextjs/package.json, nextjs/src/app/[locale]/(partners-products)/partners-products.tsx, nextjs/src/app/[locale]/theme/page.tsx, nextjs/src/app/[locale]/theme/texts.ts, nextjs/src/app/homepage.tsx, nextjs/src/app/text.css, nextjs/src/components/cards/card-colored.tsx, nextjs/src/components/cards/card-message.tsx, nextjs/src/components/nav-bar/nav-desktop-items.tsx, nextjs/src/components/nav-bar/nav-desktop.tsx, nextjs/src/components/stapi/hallmarks.tsx, strapi/package-lock.json, strapi/package.json, strapi/src/api/page-partner-and-product/content-types/page-partner-and-product/schema.json, strapi/src/api/page-partner-and-product/middlewares/populate-partner-and-products.ts, strapi/src/components/cards/kpi-card.json, strapi/src/components/sections/kpi-with-intro-and-hallmarks-section.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
- feat AW-12 missing kpi section partners products (#60)
- fix (text-section-with-cta): add missing component (#59)
- Fix: Topbar Menu backgrounds on Desktop (#58)
- feat (ci): Build checks before merge in GitHub actions (#57)
- feat: Card with Message Icon as Header (#56)
=> 0.10.0 Release

nextjs/src/app/[locale]/(partners-products)/partners-products.tsx, nextjs/src/app/[locale]/(solutions-group)/solutions.tsx, nextjs/src/app/[locale]/(solutions-group)/solutions/[slug]/page.tsx, nextjs/src/app/homepage.tsx, strapi/src/api/hero/content-types/hero/schema.json, strapi/types/generated/contentTypes.d.ts
Add optional CTA to Hero collection
=> AW-53 strapi frontend add optional cta to hero collection

nextjs/src/app/[locale]/(partners-products)/partners-products.tsx, nextjs/src/app/[locale]/(solutions-group)/solutions.tsx, nextjs/src/app/[locale]/(solutions-group)/solutions/[slug]/page.tsx, nextjs/src/app/homepage.tsx, nextjs/src/components/hero.tsx, nextjs/src/components/stapi/hero-wrapper.tsx, strapi/src/api/hero/content-types/hero/schema.json, strapi/src/api/homepage/content-types/homepage/schema.json, strapi/types/generated/contentTypes.d.ts
- Remove title from hero component, rely on markdown "body"
- Reusable HeroWrapper on each page
- Selectable hero on homepage
- Fix typo on hero component
=> AW-72 strapi hero collection refactor and fix typo

nextjs/src/app/[locale]/(solutions-group)/solutions.tsx, nextjs/src/components/dynamic-zone/render-sections.tsx, nextjs/src/components/dynamic-zone/wrapper/relations/section-solutions-relation.tsx, nextjs/src/components/dynamic-zone/wrapper/relations/sla-card-section.tsx, strapi/src/api/solutions-overview/content-types/solutions-overview/schema.json, strapi/src/api/solutions-overview/middlewares/local-hero-sections.ts, strapi/src/api/solutions-overview/routes/solutions-overview.ts, strapi/src/components/relations/section-solutions-relation.json, strapi/src/components/relations/sla-card-section.json, strapi/src/components/relations/solutions-relation-with-description.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
Enable dynamic zone on solutions overview
- new component: [relations.section-solutions-relation](https://github.com/adfinis/adfinis-website/pull/72/commits/856d3accab89679860c4c84c87fc773342f1769b)
- new component: [relations.sla-card-section wrapper](https://github.com/adfinis/adfinis-website/pull/72/commits/be2355a1de4ac7870d8066d892aad0a11c52222c)
=> AW-69 migrate solutions overview page to dynamic zone

nextjs/src/app/homepage.tsx, nextjs/src/components/dynamic-zone/render-sections.tsx, nextjs/src/components/dynamic-zone/wrapper/sections/color-card-slider-section.tsx, strapi/src/api/homepage/content-types/homepage/schema.json, strapi/src/api/homepage/routes/homepage.ts, strapi/src/components/sections/section-with-rich-heading-intro-and-cta.json, strapi/src/middlewares/populate-sections-with-intro-and-localizations.ts, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
Dynamic components for homepage
- new sections.color-card-slider-section
=> AW-70 migrate home page to dynamic zone

strapi/src/api/icon-card/content-types/icon-card/schema.json, strapi/types/generated/contentTypes.d.ts
=> feat (AW-49): add name to card collection

nextjs/src/components/dynamic-zone/render-sections.tsx, nextjs/src/components/dynamic-zone/wrapper/relations/product-cards-section.tsx, strapi/src/api/card-product/content-types/card-product/schema.json, strapi/src/api/card-product/controllers/card-product.ts, strapi/src/api/card-product/routes/card-product.ts, strapi/src/api/card-product/services/card-product.ts, strapi/src/api/homepage/content-types/homepage/schema.json, strapi/src/api/page-partner-and-product/content-types/page-partner-and-product/schema.json, strapi/src/api/page-partner-and-product/middlewares/populate-partner-and-products.ts, strapi/src/api/solutions-overview/content-types/solutions-overview/schema.json, strapi/src/api/solutions-overview/middlewares/local-hero-sections.ts, strapi/src/api/solutions-page/content-types/solutions-page/schema.json, strapi/src/api/solutions-page/middlewares/populate-basic-with-dynamic-zone.ts, strapi/src/components/relations/product-cards-section.json, strapi/src/middlewares/populate-sections-with-intro-and-localizations.ts, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
- updates strapi middlewares
- adds product cards to dynamic zones
=> AW-18 missing component solutions products

nextjs/src/components/dynamic-zone/render-sections.tsx, nextjs/src/components/dynamic-zone/wrapper/sections/info-details-section.tsx, strapi/src/api/homepage/content-types/homepage/schema.json, strapi/src/components/sections/info-details-section.json, strapi/src/middlewares/populate-sections-with-intro-and-localizations.ts, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
=> feat (AW-23): info details section

nextjs/src/components/sections/section-quote.tsx
=> AW-22 image doesnt change on quote when updated

nextjs/src/app/[locale]/(case-studies)/case-studies-overview-page.tsx, nextjs/src/app/[locale]/(case-studies)/case-studies-slugs.ts, nextjs/src/app/[locale]/(case-studies)/case-studies/[slug]/page.tsx, nextjs/src/app/[locale]/(case-studies)/case-studies/page.tsx, nextjs/src/app/[locale]/(case-studies)/case-study-detail-page.tsx, nextjs/src/app/[locale]/(case-studies)/casestudies/[slug]/page.tsx, nextjs/src/app/[locale]/(case-studies)/casestudies/page.tsx, nextjs/src/app/[locale]/(case-studies)/fallstudien/[slug]/page.tsx, nextjs/src/app/[locale]/(case-studies)/fallstudien/page.tsx, nextjs/src/components/stapi/case-studies-overview-grid-section.tsx, strapi/src/api/case-studies-overview/content-types/case-studies-overview/schema.json, strapi/src/api/case-studies-overview/controllers/case-studies-overview.ts, strapi/src/api/case-studies-overview/routes/case-studies-overview.ts, strapi/src/api/case-studies-overview/services/case-studies-overview.ts, strapi/src/api/page-case-study/content-types/page-case-study/schema.json, strapi/src/api/page-case-study/controllers/page-case-study.ts, strapi/src/api/page-case-study/routes/page-case-study.ts, strapi/src/api/page-case-study/services/page-case-study.ts, strapi/types/generated/contentTypes.d.ts
Update api roles after deployment
=> AW-34 case study detail & overview page

nextjs/src/app/[locale]/(case-studies)/case-studies-overview-page.tsx, nextjs/src/app/[locale]/(case-studies)/case-study-detail-page.tsx, nextjs/src/app/[locale]/(pages)/[...slug]/page.tsx, nextjs/src/app/[locale]/(partners-products)/partners-products.tsx, nextjs/src/app/[locale]/(solutions-group)/solution-detail.tsx, nextjs/src/app/[locale]/(solutions-group)/solutions.tsx, nextjs/src/app/[locale]/events/[slug]/page.tsx, nextjs/src/app/[locale]/events/page.tsx
Fix content filtered on published status
(duplicate pr to trigger CI)
=> fix AW-163: add filter on published content

nextjs/src/components/cards/card-member.tsx, nextjs/src/components/dynamic-zone/render-sections.tsx, nextjs/src/components/dynamic-zone/wrapper/sections/team-member-card-section.tsx, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/cards/team-member-card.json, strapi/src/components/sections/team-member-card-section.json, strapi/src/middlewares/populate-sections-with-intro-and-localizations.ts, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
=> AW-179 team page components

nextjs/src/components/dynamic-zone/render-sections.tsx, nextjs/src/components/dynamic-zone/wrapper/sections/career-card-section.tsx, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/cards/career-card.json, strapi/src/components/sections/career-card-section.json, strapi/src/middlewares/populate-sections-with-intro-and-localizations.ts, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
=> AW-169 overview for join items grid cards with flags

nextjs/package-lock.json, nextjs/package.json, nextjs/src/components/hero.tsx
https://nextjs.org/docs/messages/sharp-missing-in-production
=> AW-200 add prio to hero image and install sharp dependency

nextjs/src/components/cards/card-article.tsx, nextjs/src/components/cards/card-slider-explanation.tsx, nextjs/src/components/cards/card-slider.tsx, nextjs/src/components/dynamic-zone/wrapper/sections/content-carousel.tsx, strapi/src/components/cards/category-card.json, strapi/types/generated/components.d.ts
- Change H3 -> H2 in `cards/card-slider-explanation.tsx`
- Add arrow icon when href is provided
- Add href to strapi backend
=> AW-190 optimalisaties van content carousel component latest on

nextjs/src/app/[locale]/events/[slug]/page.tsx
=> feat AW-208: move dynamic zone components below fixed details

nextjs/src/app/(homepage)/de-ch/page.tsx, nextjs/src/app/(homepage)/de-de/page.tsx, nextjs/src/app/(homepage)/en-au/page.tsx, nextjs/src/app/(homepage)/en/page.tsx, nextjs/src/app/(homepage)/nl/page.tsx, nextjs/src/app/[...slug]/page.tsx, nextjs/src/app/[locale]/(case-studies)/case-studies/[slug]/page.tsx, nextjs/src/app/[locale]/(case-studies)/case-studies/page.tsx, nextjs/src/app/[locale]/(case-studies)/casestudies/[slug]/page.tsx, nextjs/src/app/[locale]/(case-studies)/casestudies/page.tsx, nextjs/src/app/[locale]/(case-studies)/referenzen/[slug]/page.tsx, nextjs/src/app/[locale]/(case-studies)/referenzen/page.tsx, nextjs/src/app/[locale]/(news)/news/[slug]/page.tsx, nextjs/src/app/[locale]/(news)/news/page.tsx, nextjs/src/app/[locale]/(news)/nieuws/[slug]/page.tsx, nextjs/src/app/[locale]/(news)/nieuws/page.tsx, nextjs/src/app/[locale]/(pages)/[...slug]/page.tsx, nextjs/src/app/[locale]/(partners-products)/partner-und-produkte/[slug]/page.tsx, nextjs/src/app/[locale]/(partners-products)/partners-and-products/[slug]/page.tsx, nextjs/src/app/[locale]/(partners-products)/partners-en-producten/[slug]/page.tsx, nextjs/src/app/[locale]/(solutions-group)/loesungen/[slug]/page.tsx, nextjs/src/app/[locale]/(solutions-group)/loesungen/page.tsx, nextjs/src/app/[locale]/(solutions-group)/oplossingen/[slug]/page.tsx, nextjs/src/app/[locale]/(solutions-group)/oplossingen/page.tsx, nextjs/src/app/[locale]/(solutions-group)/solutions/[slug]/page.tsx, nextjs/src/app/[locale]/(solutions-group)/solutions/page.tsx, nextjs/src/app/[locale]/events/[slug]/page.tsx, nextjs/src/app/[locale]/events/page.tsx, nextjs/src/app/page.tsx
- add hreflang for i18n collections
- fixes missing meta-description on some overview pages
=> AW-284 hreflang semrush issue

nextjs/next.config.mjs
and removed not needed redirect
=> AW-291 slug issue in icon card section red hat page

CHANGELOG.md, nextjs/package-lock.json, nextjs/package.json, nextjs/src/app/(homepage)/de-ch/page.tsx, nextjs/src/app/(homepage)/de-de/page.tsx, nextjs/src/app/(homepage)/en-au/page.tsx, nextjs/src/app/(homepage)/en/page.tsx, nextjs/src/app/(homepage)/nl/page.tsx, nextjs/src/app/page.tsx, strapi/package-lock.json, strapi/package.json
- fix (AW-305): fixed typo for metadata description (#272)
=> Release 1.5.2

CHANGELOG.md, nextjs/package-lock.json, nextjs/package.json, nextjs/src/components/matomo/matomo-tag-manager.tsx, strapi/package-lock.json, strapi/package.json
- fix (AW-296): try running matomo with onLoad prop
=> Release 1.6.1
